#!/bin/bash
# configure_ios.sh
# Generates ios/Flutter/TenantConfig.xcconfig with tenant-specific values.
# Run this script BEFORE `flutter build ipa` in the CI pipeline.
#
# Required env vars:
#   BUNDLE_ID_IOS   e.g. com.minha-loja.app
#   APP_NAME        e.g. Minha Loja
#
# Example (Codemagic pre-build script):
#   ./scripts/configure_ios.sh

set -e

BUNDLE_ID="${BUNDLE_ID_IOS:-com.havix.devstore}"
APP_NAME="${APP_NAME:-Havix Dev Store}"
XCCONFIG="ios/Flutter/TenantConfig.xcconfig"

echo "// Auto-generated by configure_ios.sh — do not edit manually" > "$XCCONFIG"
echo "PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID" >> "$XCCONFIG"
echo "APP_DISPLAY_NAME = $APP_NAME" >> "$XCCONFIG"

echo "✅ iOS configured: bundle=$BUNDLE_ID app='$APP_NAME'"
